blank_issues_enabled: false

contact_links:
- name: Get help in GitHub Discussions
  url: https://github.com/Homebrew/discussions/discussions
  about: Have a question? Not sure if your issue affects everyone reproducibly? The quickest way to get help is on Homebrew's GitHub Discussions!
- name: New issue on Homebrew/brew
  url: https://github.com/Homebrew/brew/issues/new/choose
  about: Having a `brew` problem that's not from a `brew install` or `brew upgrade` of a single formula/package?
- name: New issue on Homebrew/homebrew-core
  url: https://github.com/Homebrew/homebrew-core/issues/new/choose
  about: On macOS/Mac OS X? Having a `brew` problem with a `brew install` or `brew upgrade` of a single formula/package? Report it to Homebrew/homebrew-core (the macOS core tap/repository).
- name: New issue on Homebrew/homebrew-cask
  url: https://github.com/Homebrew/homebrew-cask/issues/new/choose
  about: Having a `brew --cask` problem? Report it to Homebrew/homebrew-cask (the cask tap/repository).
- name: New issue on Homebrew/linuxbrew-core
  url: https://github.com/Homebrew/linuxbrew-core/issues/new/choose
  about: On Linux? Having a `brew` problem with a `brew install` or `brew upgrade` of a single formula/package? Report it to Homebrew/linuxbrew-core (the Linux core tap/repository).
